name: build and publish
on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - run: |
          npm i -g yarn
          yarn && yarn build
          rm -rf /tmp/.buildx-cache
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: blockless/wasi-repo:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
